cdbranch-defaults:
  default:
    environment: X21164967flightbooking-env
environment-defaults:
  211549292-ebdjango:
    branch: null
    repository: null
  21154929dj-env:
    branch: null
    repository: null
  21154929eb-env:
    branch: null
    repository: null
global:
  application_name: x21164967-FlightBooking
  default_ec2_keyname: null
  default_platform: Python 3.7
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application